### ISSUE TITLE
Reinit after system ttl 

### ISSUE THREAD

**Issue by alexey13** [RonenNess/partykals#3]
Good day! Big thanks for awesome particles for threejs!
Can you please tell what the best way to reinit system after ttl has expired?
Dispose and push new one?

**Comment by RonenNess** [comment]
Hi @alexey13, try `system.reset()`

https://github.com/RonenNess/partykals/blob/master/dist/partykals.js#L876

**Comment by skybluecat** [comment]
Hi, how to reset the system and cause it to emit particles again if the emitter is set to emit only once (using onSpawnBurst)?
