### ISSUE TITLE
Not working with Webpack

### ISSUE THREAD

**Issue by NeoHoffa** [RonenNess/partykals#9]
Can this work with Webpack? 

I'm using this THREE.js boilerplate. 
[https://github.com/ethanny2/threejs-es6-webpack-barebones-boilerplate](https://github.com/ethanny2/threejs-es6-webpack-barebones-boilerplate)

**Comment by RonenNess** [comment]
Have you tried using `import`?

**Comment by RonenNess** [comment]
See https://github.com/RonenNess/partykals/issues/5
Either include as another script tag in your HTML, or add the required wrapper needed for import. Someone already did it you can fork them.

Thanks
